### ISSUE TITLE
GetPageWidth() function gone?

### ISSUE THREAD

**Issue by zoomyboy** [DocnetUK/tfpdf#14]
Hi!

This is definately an amazing project in my opinion - BUT as soon as I use this with my old Fpdf documents I get the error that the method "GetPageWidth" wasn't found. Is there any workaround for this or did you just replace the old function name with a newer one?

**Comment by kazsaj** [comment]
Hi @zoomyboy 

Would you be able to point me to a version that has this method? I might be able to port it.

**Comment by SharkMachine** [comment]
It's a new method added in FPDF 1.81 and not present in tFPDF. Adding following methods should work with tFPDF:

```php
/**
 * Get current page width
 * @return float
 */
public function GetPageWidth()
{
    return $this->flt_current_width;
}

/**
 * Get current page height
 * @return float
 */
public function GetPageHeight()
{
    return $this->flt_current_height;
}
```

**Comment by kazsaj** [comment]
This has been added to the 2.2.0 release:
https://github.com/DocnetUK/tfpdf/releases/tag/v2.2.0
