### ISSUE TITLE
Setting color with one parameter not working

### ISSUE THREAD

**Issue by SharkMachine** [DocnetUK/tfpdf#33]
It seems that setting color with one parameter was broken in 2.2.0 release.

**Example script:**

```php
<?php
require 'vendor/autoload.php';

// Init
$pdf = new \tFPDF\PDF();
$pdf->AddPage();
$pdf->AddFont('DejaVuSans', '', 'DejaVuSans.ttf', true);
$pdf->SetFont('DejaVuSans', '', 25);
$pdf->SetLineWidth(2);

// Set draw color example
$pdf->SetDrawColor(100);
$pdf->Line(20, 20, 200, 20);

// Set fill color example
$pdf->SetFillColor(100);
$pdf->Rect(20, 30, 180, 20, 'F');

// Set text color example
$pdf->SetTextColor(100);
$pdf->Text(20, 70, 'Test text');

file_put_contents('test.pdf', $pdf->output());
```

**Expected result:**

[2.1.1_result.pdf](https://github.com/DocnetUK/tfpdf/files/2735750/2.1.1_result.pdf)

**Actual result:**

[2.2.1_result.pdf](https://github.com/DocnetUK/tfpdf/files/2735751/2.2.1_result.pdf)

**Comment by kazsaj** [comment]
Thanks for raising, this should be resolved in https://github.com/DocnetUK/tfpdf/releases/tag/v2.2.2

There was a change in 2.2.0, that started expecting 0-100 values for the grayscale colours. Since it might break a lot of old stuff, I've reverted it to use 0-255.

**Comment by SharkMachine** [comment]
2.2.2 resolves the issue, thanks
